name: Windows Task

on: [push]

jobs:
  run-on-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: |
          echo "Hello from GitHub Actions on Windows!"
        
      - name: Open Notepad
        run: |
          Start-Process notepad.exe
